[tool.poetry]
name = "celestia-data-pipeline"
version = "0.1.0"
description = "Contains all of the relevant code for running the Celestia data pipeline."
authors = ["Cody Kilpatrick <Codykilpatrick1996@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "^1.26.1"
pandas = "^2.1.2"
asyncpg = "^0.28.0"
psycopg2 = "^2.9.9"
python-dotenv = "^1.0.0"
aiohttp = "^3.8.6"
requests = "^2.31.0"
joblib = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
