name: Commit Neon Dump
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  commit_neon_dump:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
      - name: Dump database
        run: |
          pg_dump -Fc -v -d postgres://${{ secrets.NEON_USER }}:${{ secrets.NEON_PASSWORD }}@${{ secrets.NEON_HOST }}/${{ secrets.DATABASE }} -f ./packages/celestia-database/db_dumps/celestia_dump.sql
      - name: Git Add/Commit database dump
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "./packages/celestia-database/db_dumps/celestia_dump.sql --force"
          commit: -S
          committer_email: codykilpatrick1996@gmail.com
          committer_name: Codykilpatrick
          message: "Commit current database dump [skip ci]"
          pull: --rebase --autostash
          push: origin ${{ github.head_ref }} --set-upstream
