name: Daily Market History Pull
on:
  schedule:
    - cron: "0 0 * * *"
  # pull_request:
  #   branches:
  #     - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11
          cache: poetry
      - name: Install project dependencies
        run: |
          poetry install
        working-directory: packages/celestia-models
      - name: Run Python script
        env:
          NEON_CONNECTION_STRING: ${{ secrets.NEON_CONNECTION_STRING }}
          DATABASE: ${{ secrets.DATABASE }}
          NEON_USER: ${{ secrets.NEON_USER }}
          NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
          NEON_HOST: ${{ secrets.NEON_HOST }}
          NEON_PORT: ${{ secrets.NEON_PORT }}
        run: |
          poetry run python predict_daily_average.py
        working-directory: packages/models/pipeline